name: api_mock
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^0.13.3
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.3 
  flutter_local_notifications: ^14.1.1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: 1.1.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true